version: '3.3'
services:
  db:
    image: postgres:13.3
    environment:
      POSTGRES_DB: "drive-pet"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      PGDATA: /var/lib/postgresql/data/pgdata
    ports:
      - "5432:5432"
    expose:
      - "5432"
    restart: on-failure
    volumes:
      - /Users/{username}/volumes/postgres

  localstack:
    image: localstack/localstack:latest
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
      - AWS_ACCESS_KEY_ID=accessKey
      - AWS_SECRET_ACCESS_KEY=secretKey
    volumes:
      - ./localstack-setup.sh:/etc/localstack/init/ready.d/script.sh
