-- init tables

create table if not exists drive_user
(
    id         bigint generated by default as identity
        primary key,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,

    email      varchar(255) not null,
    password   varchar(255) not null,
    first_name varchar(255) not null,
    last_name  varchar(255) not null,
    role       varchar(255) not null
);

create table if not exists folder
(
    id         uuid default gen_random_uuid() not null
        primary key,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,

    name       varchar(255)                   not null,

    user_id    bigint                         not null,
    folder_id  uuid default gen_random_uuid()
);

create table if not exists file
(
    id         uuid default gen_random_uuid() not null
        primary key,
    created_at timestamp(6) with time zone,
    updated_at timestamp(6) with time zone,

    file_name  varchar(255)                   not null,
    file_type  varchar(255)                   not null,
    path       varchar(1023)                  not null,
    size       bigint                         not null,

    user_id    bigint                         not null,
    folder_id  uuid default gen_random_uuid()
);

-- create foreign keys

alter table file
    drop constraint if exists fk_file_user;
alter table file
    add constraint fk_file_user
        foreign key (user_id)
            references drive_user (id);

alter table folder
    drop constraint if exists fk_folder_user;
alter table folder
    add constraint fk_folder_user
        foreign key (user_id)
            references drive_user (id);

alter table file
    drop constraint if exists fk_file_folder;
alter table file
    add constraint fk_file_folder
        foreign key (folder_id)
            references folder (id);

alter table folder
    drop constraint if exists fk_folder_folder;
alter table folder
    add constraint fk_folder_folder
        foreign key (folder_id)
            references folder (id);
