-- file access

create table if not exists user_to_file_access
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    updated_at  timestamp(6) with time zone,

    file_id     uuid         not null,
    user_id     bigint       not null,
    access_type varchar(255) not null
);

alter table user_to_file_access
    drop constraint if exists fk_user_to_file_access_file;
alter table user_to_file_access
    add constraint fk_user_to_file_access_file
        foreign key (file_id)
            references file (id);

alter table user_to_file_access
    drop constraint if exists fk_user_to_file_user;
alter table user_to_file_access
    add constraint fk_user_to_file_user
        foreign key (user_id)
            references drive_user (id);

insert into user_to_file_access (created_at, updated_at, file_id, user_id, access_type)
select f.created_at, f.created_at, f.id, f.user_id, 'OWNER'
from file f;

-- folder access

create table if not exists user_to_folder_access
(
    id          bigint generated by default as identity
        primary key,
    created_at  timestamp(6) with time zone,
    updated_at  timestamp(6) with time zone,

    folder_id   uuid         not null,
    user_id     bigint       not null,
    access_type varchar(255) not null
);

alter table user_to_folder_access
    drop constraint if exists fk_user_to_folder_access_folder;
alter table user_to_folder_access
    add constraint fk_user_to_folder_access_folder
        foreign key (folder_id)
            references folder (id);

alter table user_to_folder_access
    drop constraint if exists fk_user_to_folder_access_user;
alter table user_to_folder_access
    add constraint fk_user_to_folder_access_user
        foreign key (user_id)
            references drive_user (id);

insert into user_to_folder_access (created_at, updated_at, folder_id, user_id, access_type)
select f.created_at, f.created_at, f.id, f.user_id, 'OWNER'
from folder f;

-- item view

drop view if exists item_view;

create or replace view item_view as
select item.*
from (select fil.id           as id,
             fil.file_name    as name,
             'FILE'           as type,
             fil.size         as size,
             fil.folder_id    as folder_id,
             utfia.user_id    as owner_id,
             fil.created_at   as created_at,
             fil.updated_at   as updated_at,
             fil.s3_file_path as path,
             fil.file_type    as file_type
      from file fil
               join user_to_file_access utfia on fil.id = utfia.file_id and utfia.access_type = 'OWNER'
      union
      select fol.id         as id,
             fol.name       as name,
             'FOLDER'       as type,
             null           as size,
             fol.folder_id  as folder_id,
             utfoa.user_id  as owner_id,
             fol.created_at as created_at,
             fol.updated_at as updated_at,
             null           as path,
             null           as file_type
      from folder fol
               join user_to_folder_access utfoa on fol.id = utfoa.folder_id and utfoa.access_type = 'OWNER') item;

-- remove redundant

alter table file
    drop column user_id;

alter table folder
    drop column user_id;
